apiVersion: apps/v1
kind: Deployment
metadata:
  name: defect-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defect-detection
  template:
    metadata:
      labels:
        app: defect-detection
    spec:
      containers:
      - name: defect-detection
        image: chintaguntavv/defect-detection:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: defect-detection-service
spec:
  type: NodePort   # use LoadBalancer only in cloud clusters
  selector:
    app: defect-detection
  ports:
  - port: 80
    targetPort: 8000
